services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: frontend
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${PORT}:${PORT}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
